# .github/workflows/test.yml

name: Test

on: workflow_dispatch

jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 10.1.1
      - name: Lint
        run: inso --version
